version: '3.4'

services:
  postgres:
    image: postgres:11-alpine
    shm_size: 4g
    environment:
      POSTGRES_PASSWORD: foo
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:rw
  redis:
    image: redis:latest
    restart: always
    command: ["redis-server"]
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./data/redis:/usr/local/etc/redis
